spring:
  application:
      name: oa-check
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/oa-check?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    driver-class-name:  com.mysql.jdbc.Driver
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/oa-check?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    encoding: UTF-8
    enabled: true
    suffix: .html
    prefix: classpath:/templates/
    enable-spring-el-compiler: true #使用El
  jpa:
    show-sql: true
 # 服务模块
  devtools:
    restart:
      enabled: true
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /
      suffix: .html

# 开发环境配置
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30

# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.ck
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mapping/*.xml
    configuration:
      cache-enabled: true
      use-generated-keys: true
      default-executor-type: reuse
      map-underscore-to-camel-case: true

# pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# 日志配置
# 打印sql
logging:
  level:
     com.ck.syscheck.dao : debug

